import type { StaticAttributeDef } from "../types/workflow-persistence";

import type { CanvasNodeLike } from "./device-param-hints";

const GET_FROM_USER_KIND = "get-from-user";

/** Names referenced by ``get-from-user`` nodes' ``device_param`` config. */
export function collectGetFromUserDeviceParams(nodes: CanvasNodeLike[]): string[] {
  const names: string[] = [];
  const seen = new Set<string>();

  for (const node of nodes) {
    if (node.data?.kind !== GET_FROM_USER_KIND) {
      continue;
    }
    const raw = node.data.pluginConfig?.device_param;
    const name = typeof raw === "string" ? raw.trim() : "";
    if (!name || seen.has(name)) {
      continue;
    }
    seen.add(name);
    names.push(name);
  }

  return names;
}

/** The exact shape this module auto-generates for a ``get-from-user``
 * ``device_param`` (see the loop below). Used to recognize — and only ever
 * prune — an attribute this code created itself; a hand-customized
 * attribute (a different type, ``required: false``, a ``default``, or a
 * ``ref_kind``) never matches and is never touched. */
function isAutoGeneratedRunInputShape(attr: StaticAttributeDef): boolean {
  return (
    attr.type === "string" &&
    attr.required === true &&
    (attr.default === undefined || attr.default === null) &&
    !attr.ref_kind
  );
}

/**
 * Reconcile workflow-declared static attributes with the run-parameter names
 * currently required by ``get-from-user`` steps:
 *
 * - adds a missing ``string`` / ``required: true`` entry for each
 *   referenced ``device_param``;
 * - drops a previously auto-added entry once its ``device_param`` no longer
 *   matches any ``get-from-user`` node (the node was deleted, or
 *   ``device_param`` was renamed) — see ``isAutoGeneratedRunInputShape``.
 *
 * A hand-customized declaration always wins: it survives being unreferenced
 * as long as it doesn't have the exact auto-generated shape.
 */
export function mergeRunInputAttributes(
  nodes: CanvasNodeLike[],
  staticAttributes: StaticAttributeDef[],
): StaticAttributeDef[] {
  const activeParams = new Set(collectGetFromUserDeviceParams(nodes));
  const byName = new Map<string, StaticAttributeDef>();

  for (const attr of staticAttributes) {
    const trimmed = attr.name.trim();
    if (!trimmed) {
      continue;
    }
    if (!activeParams.has(trimmed) && isAutoGeneratedRunInputShape(attr)) {
      continue;
    }
    byName.set(trimmed, { ...attr, name: trimmed });
  }

  for (const param of activeParams) {
    if (!byName.has(param)) {
      byName.set(param, { name: param, type: "string", required: true });
    }
  }

  return Array.from(byName.values());
}

export function staticAttributesEqual(
  a: StaticAttributeDef[],
  b: StaticAttributeDef[],
): boolean {
  if (a.length !== b.length) {
    return false;
  }
  const sortKey = (attrs: StaticAttributeDef[]) =>
    [...attrs]
      .map((attr) => JSON.stringify(attr))
      .sort()
      .join("\0");
  return sortKey(a) === sortKey(b);
}

export function validateGetFromUserNodes(nodes: CanvasNodeLike[]): string[] {
  const issues: string[] = [];

  for (const node of nodes) {
    if (node.data?.kind !== GET_FROM_USER_KIND) {
      continue;
    }
    const raw = node.data.pluginConfig?.device_param;
    const param = typeof raw === "string" ? raw.trim() : "";
    const label =
      typeof node.data?.title === "string" && node.data.title.trim()
        ? node.data.title.trim()
        : "Get from User";
    if (!param) {
      issues.push(`${label}: set device_param to the run parameter name for the device list.`);
    }
  }

  return issues;
}
