import type {
  WorkflowCanvasEdge,
  WorkflowCanvasNode,
} from "../types/workflow-canvas";

export const initialWorkflowNodes: WorkflowCanvasNode[] = [
  {
    id: "get-nautobot-devices",
    type: "workflowNode",
    position: { x: 80, y: 210 },
    data: {
      kind: "get-nautobot-devices",
      title: "Get from Nautobot",
      description: "Choose target devices from inventory.",
      artifactType: "inventory_selector",
      mandatoryInputs: [],
      outcomes: ["success", "failure"],
      status: "ready",
    },
  },
  {
    id: "get-configs",
    type: "workflowNode",
    position: { x: 390, y: 210 },
    data: {
      kind: "get-configs",
      title: "Get Configs",
      description: "Retrieve device configuration.",
      artifactType: "configuration_retrieval",
      mandatoryInputs: ["selected_devices"],
      outcomes: ["success", "failure"],
      status: "draft",
    },
  },
  {
    id: "condition",
    type: "workflowNode",
    position: { x: 700, y: 210 },
    data: {
      kind: "condition",
      title: "Validate Output",
      description: "Check whether configuration output is usable.",
      artifactType: "control_flow",
      mandatoryInputs: ["input_reference"],
      condition: "output.length > 0",
      outcomes: ["true", "false", "failure"],
      status: "warning",
    },
  },
  {
    id: "store-artifact",
    type: "workflowNode",
    position: { x: 1010, y: 120 },
    data: {
      kind: "store-artifact",
      title: "Store Backup",
      description: "Persist configuration as an artifact.",
      artifactType: "persistent_artifact",
      mandatoryInputs: ["content_reference"],
      artifactPath: "/backups/{device}/running.cfg",
      outcomes: ["success", "failure"],
      status: "draft",
    },
  },
  {
    id: "result",
    type: "workflowNode",
    position: { x: 1010, y: 310 },
    data: {
      kind: "result",
      title: "Result",
      description: "Expose status, metadata, and content.",
      artifactType: "result",
      mandatoryInputs: ["metadata"],
      outcomes: [],
      status: "success",
    },
  },
];

export const initialWorkflowEdges: WorkflowCanvasEdge[] = [
  {
    id: "get-nautobot-devices-to-get-configs",
    type: "waypoint",
    source: "get-nautobot-devices",
    sourceHandle: "success",
    target: "get-configs",
    animated: false,
  },
  {
    id: "get-configs-to-condition",
    type: "waypoint",
    source: "get-configs",
    sourceHandle: "success",
    target: "condition",
    animated: false,
  },
  {
    id: "condition-to-store-artifact",
    type: "waypoint",
    source: "condition",
    sourceHandle: "true",
    target: "store-artifact",
    label: "valid",
    animated: false,
  },
  {
    id: "condition-to-result",
    type: "waypoint",
    source: "condition",
    sourceHandle: "false",
    target: "result",
    label: "failed",
    animated: false,
  },
];
