/**
 * Fact keys Batfish's validate_facts/extract_facts support, per Batfish's own
 * published fact schema (also documented in the Validate Facts Help tab).
 */
export const BATFISH_FACT_KEYS = [
  "AS_Path_Access_Lists",
  "Authentication_Key_Chains",
  "Canonical_IP",
  "Community_Match_Exprs",
  "Community_Set_Exprs",
  "Community_Set_Match_Exprs",
  "Community_Sets",
  "Configuration_Format",
  "Default_Cross_Zone_Action",
  "Default_Inbound_Action",
  "DNS_Servers",
  "DNS_Source_Interface",
  "Domain_Name",
  "Hostname",
  "IKE_Phase1_Keys",
  "IKE_Phase1_Policies",
  "IKE_Phase1_Proposals",
  "Interfaces",
  "IP_Access_Lists",
  "IP_Spaces",
  "IP6_Access_Lists",
  "IPsec_Peer_Configs",
  "IPsec_Phase2_Policies",
  "IPsec_Phase2_Proposals",
  "IPSec_Vpns",
  "Logging_Servers",
  "Logging_Source_Interface",
  "NTP_Servers",
  "NTP_Source_Interface",
  "PBR_Policies",
  "Route_Filter_Lists",
  "Route6_Filter_Lists",
  "Routing_Policies",
  "SNMP_Source_Interface",
  "SNMP_Trap_Servers",
  "TACACS_Servers",
  "TACACS_Source_Interface",
  "VRFs",
  "Zones",
] as const;
